- name: Download Azure Artifacts
  shell: az artifacts universal download --organization "https://dev.azure.com/DevOps-Batches/" --project "ce99914a-0f7d-4c46-9ccc-e4d025115ea9" --scope project --feed "devopsb51" --name "{{COMPONENT}}" --version "*" --path "{{ARTIFACT_PATH}}"
